before_script:
  - go get
  - make setup
  - make update

test:
  stage: test
  script:
    - go get github.com/stretchr/testify/assert
    - make testsuite
  tags:
    - go

build:
  stage: build
  script:
    - make install-home
    - make package-setup
    - make package
  tags:
    - go
