stages:
  - test
  - build

variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

before_script:
  - go get
  - make setup
  - make update
  - service docker start

test:
  stage: test
  script:
    - go get github.com/stretchr/testify/assert
    - make testsuite
  tags:
    - go

build:
  stage: build
  script:
    - make install-home
    - make package-setup
    - make package
  artifacts:
    paths:
      - build/upload/*
  tags:
    - go

push_to_github:
    stage: build
    when: manual
    script:
        - bash -c "git remote remove github; exit 0"
        - git status
        - git remote add github $GIT_HUB_URL
        - git config --global user.email "noreply@teamwork.net"
        - git config --global user.name "TeamWork"
        - git checkout master
        - git pull origin master
        - git status
        - bash -c "git push --force github master 2>&1 | grep -v github; echo $?"
        - git remote remove github
