image: golang

variables:
  PROJECT_NAMESPACE: "/go/src/git.teamwork.net/$CI_NAMESPACE"

before_script:
  - pwd
  - mkdir -p $PROJECT_NAMESPACE
  - ln -s $(pwd) $PROJECT_NAMESPACE
  - ls -l $PROJECT_NAMESPACE
  - cd $PROJECT_NAMESPACE/$CI_PROJECT_NAME
  - ls -l
  - go get
  - make setup
  - ls -l
  - make update
  - ls -l


build:
  stage: build
  script:
    - ls -l
    - pwd